### ISSUE TITLE
Python 3.7.2 bug on import

### ISSUE THREAD

**Issue by KyferEz** [j4321/tkColorPicker#5]
Your sample code produces an error with Python 3.7 installed.

```
Traceback (most recent call last):
  File "C:\Programs\tk_colorpicker.py", line 3, in <module>
    from tkcolorpicker import askcolor
  File "C:\Programs\Python37\lib\site-packages\tkcolorpicker\__init__.py", line 21, in <module>
    from tkcolorpicker.colorpicker import ColorPicker, askcolor
  File "C:\Programs\Python37\lib\site-packages\tkcolorpicker\colorpicker.py", line 23, in <module>
    from PIL import ImageTk
ModuleNotFoundError: No module named 'PIL'
```

The sample code used:
```
import tkinter as tk
import tkinter.ttk as ttk
from tkcolorpicker import askcolor

root = tk.Tk()
style = ttk.Style(root)
style.theme_use('clam')

print(askcolor((255, 255, 0), root))
root.mainloop()
```

**Comment by j4321** [comment]
Have you installed tkcolorpicker? If yes, how (pip, ubuntu package ...)?

The error you get is because the module [Pillow](https://pypi.org/project/Pillow/) is not installed on your computer. If you haven't installed tkcolorpicker, then this is not a bug, you are just missing one of the required packages. I will make the requirement section clearer in the README.

**Comment by KyferEz** [comment]
I have installed tkcolorpicker using pip and get this error, that is why I
created the bug.

**Comment by j4321** [comment]
Thanks for reporting this, I had fixed the ``install_requires`` field in setup.py some time ago but never published the corrected version on pip. The proper version is online now.
